[package]
name = "rust-mlx"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
hf-hub = "0.4.3"
memmap2 = "0.9.8"
mlx-rs = "0.25.1"
safetensors = "0.6.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokenizers = "0.22.1"
